### PR TITLE
very basic example of notes compatibility

### PR DESCRIPTION
**Pull request by rquast**
A very simple example of how to use notes. Also tested by importing notes from freemind.

### CODE REVIEW

**Comment by rquast** [comment]
Needs a html editor and some cleaning up.

**Comment by rquast** [comment]
should be enough to be useful now.. still needs sanitizing though.

**Comment by ondras** [comment]
Wow, thanks a lot @rquast , this is big! I am going to merge this.

I am not sure if including the editor (never heard of pell, thanks for the find!) is the best idea. What is your opinion on including the relevant files using e.g. unpkg, jsdelivr or similar CDN service?

**Comment by rquast** [comment]
Yeah I originally started with unpkg as a CDN, but thought that it might be wiser to include the source in the program if it doesn't stay maintained. Could use something like a simple npm package.json, if you're okay with me adding it. Maybe even migrate the makefile to package.json scripts (keep it as simple as possible). What do you think?

**Comment by ondras** [comment]
> Yeah I originally started with unpkg as a CDN, but thought that it might be wiser to include the source in the program if it doesn't stay maintained.

I don't think this is a risk really. CDN will provide a reasonable cached version even if the package gets obsoleted and unmaintained.



>  Could use something like a simple npm package.json, if you're okay with me adding it.

No problem, but why? The dependency on pell can be expressed directly in the HTML file via a `<script src=unpkg/pell.js>`...




> Maybe even migrate the makefile to package.json scripts (keep it as simple as possible).

Will this bring any improvement/change at all? Individual source files still need to be concatenated in a particular order (poor design choice, I know), so you will end up with the very same source file list, just in the `scripts` section of package.json...

**Comment by rquast** [comment]
No problems. I'll revert it back to the CDN and also stick the editor in a sandboxed iframe in the next commit to help avoid XSS issues.

**Comment by ondras** [comment]
Great, thanks! Shall I expect more commits with this functionality, or is this ready to be merged?

**Comment by rquast** [comment]
I think it should be okay to merge. I'll add another PR later to allow for editing the notes HTML, and for clearing formatting. Also would like to add something to sanitize pasted html, but this may be a bit difficult without an external library. I'll give it a go on browserstack and let you know how well it works with different browsers.

**Comment by rquast** [comment]
Just tried IE11 and it failed. Will fix.

**Comment by watoo** [comment]
Hi,
How can we make these notes readonly?

**Comment by watoo** [comment]
I have a variable in my-mind.js says "isReadOnly", I have made the nodes read-only by managing the keyboard events, but couldn't find a way for notes. The contentEditable property is also not working. Can you please help?

**Comment by ondras** [comment]
Looks like this got stuck somehow. Please, @rquast , what is the status here?

**Comment by 7dir** [comment]
cannot paste from clipboard to node with nodes

**Comment by ZiadJ** [comment]
@ondras If IE11 support is the only issue then we don't really need it since support for it is about to be dropped by Microsoft itself.

image

**Comment by ondras** [comment]
Agreed, but we are still waiting for @rquast's opinion/statement here.

**Comment by rquast** [comment]
@ZiadJ I agree - I don't think there's a need to support IE11 anymore. I've used this PR myself frequently and there aren't too many major issues with it. I think we can merge and create another branch for adding things like read only and a fix for pasting.

**Pull request merged**
