### PR TITLE
Add font color picker in Typescript

### PR DESCRIPTION
**Pull request by 0kyn**
Hey @ondras,

I give it a try with the new Typscript impl. It's a huge refactoring!

This PR should close https://github.com/ondras/my-mind/pull/133

### CODE REVIEW

**Review by 0kyn — COMMENTED** [review]
It seems last esbuild@0.13.11 release inject the following decorators

commit : https://github.com/evanw/esbuild/commit/859382ee08bed008080cee7d378c5ead87dac9e9#diff-dfb217f99ae89452063f7bc651da92476ba387fc6de37495c98096ad67f5ba10R79-R80

**Comment by ondras** [comment]
Hmm, is there anything wrong with those decorators?

**Comment by 0kyn** [comment]
There were injected by esbuild@0.13.11 at build time, but unused in `my-mind.js` so I removed them.

**Comment by ondras** [comment]
> There were injected by esbuild@0.13.11 at build time, but unused in `my-mind.js` so I removed them.

I see. Well, they will get injected every time `make` runs, so removing them is kinda sisyphean task...

**Comment by 0kyn** [comment]
There is probably a better way to handle this, or even not handle this and let esbuild inject what it wants/needs..

**Comment by ondras** [comment]
LGTM, thanks a lot @0kyn !

**Comment by ondras** [comment]
I made some adjustments in https://github.com/ondras/my-mind/commit/76c8fa98c50bc31280dd18d0ccb934e62bfd405c:
  - renamed "font color" to "text color"
  - default is now `""` (which removes the style property so the color gets correctly inherited)
  - i switched the color/textcolor UI elements so that the text color is 2nd

**Pull request merged**
